In [184]:
import pandas as pd
import numpy as np
X_train = pd.read_csv("../features/global_features/X_train.csv")
y_train = pd.read_csv("../features/global_features/y_train.csv")
X_test = pd.read_csv("../features/global_features/X_test.csv")
SEUIL = 0. #0.069
SEUIL_clip = 0.05 #0.14
SEUIL_OLD = 1
SEUIL_AUDIO = 1

In [185]:
X_train.head()

,video_id,f1_sharpness_x,f1_brightness_x,f1_saturation_x,f2_sharpness_x,f2_brightness_x,f2_saturation_x,f3_sharpness_x,f3_brightness_x,f3_saturation_x,...,c510_y,c511_y,avg_face_count_y,max_face_coverage_y,body_presence_score_y,dominant_emotion_angry_y,dominant_emotion_fear_y,dominant_emotion_happy_y,dominant_emotion_neutral_y,dominant_emotion_none_y
0,6739804771013774597,790.54,159.49,58.70,782.57,159.14,59.44,520.51,151.33,62.68,...,0.1798,-0.1307,0.000000,0.0000,0.000000,False,False,False,False,True
1,6750983141873224966,106.36,132.97,74.63,141.68,144.24,63.61,200.35,145.59,67.48,...,0.1899,-0.0035,0.333333,0.0011,0.333333,False,False,False,False,True
2,6792131260543225094,473.91,121.51,118.76,417.19,119.68,120.22,NaN,NaN,NaN,...,0.4097,-0.0977,0.000000,0.0000,0.000000,False,False,False,False,True
3,6792133610360065285,348.03,141.39,39.86,436.69,139.93,39.24,210.11,141.28,29.63,...,0.1552,0.1190,0.333333,0.0005,0.333333,False,False,False,False,True
4,6793347939294072069,163.05,153.17,130.20,151.03,158.77,121.23,NaN,NaN,NaN,...,0.3197,-0.1434,0.000000,0.0000,0.000000,False,False,False,False,True

In [186]:
X_train_video = X_train.iloc[:,np.r_[1:23, 535:547, 609:632]]
X_train_video.head()

,f1_sharpness_x,f1_brightness_x,f1_saturation_x,f2_sharpness_x,f2_brightness_x,f2_saturation_x,f3_sharpness_x,f3_brightness_x,f3_saturation_x,f4_sharpness,...,att_mean_saliency,att_max_saliency,att_min_saliency,att_skewness,att_kurtosis,att_hook_score,att_outro_score,att_peak_location,att_high_attention_ratio,att_attention_instability
0,790.54,159.49,58.70,782.57,159.14,59.44,520.51,151.33,62.68,261.36,...,18.507618,22.806738,10.112532,-1.205898,2.290891,19.101084,17.134331,0.576923,0.961538,1.628250
1,106.36,132.97,74.63,141.68,144.24,63.61,200.35,145.59,67.48,66.86,...,17.008192,21.973700,12.307789,0.156576,-0.054742,13.983650,18.627373,0.545455,0.954545,1.496439
2,473.91,121.51,118.76,417.19,119.68,120.22,NaN,NaN,NaN,NaN,...,16.193535,20.542313,13.786904,0.872993,0.066454,17.384562,15.784161,0.192308,1.000000,0.600385
3,348.03,141.39,39.86,436.69,139.93,39.24,210.11,141.28,29.63,283.59,...,14.890491,18.952852,11.925114,0.715640,0.095493,17.447706,15.095791,0.800000,0.920000,1.379394
4,163.05,153.17,130.20,151.03,158.77,121.23,NaN,NaN,NaN,NaN,...,15.241565,17.432913,12.499903,-0.753328,-0.171700,15.479694,16.617624,0.913043,0.869565,0.853227

In [187]:
X_train_clip = X_train.iloc[:,23:535]
X_train_clip.head()

,c0_x,c1_x,c2_x,c3_x,c4_x,c5_x,c6_x,c7_x,c8_x,c9_x,...,c502_x,c503_x,c504_x,c505_x,c506_x,c507_x,c508_x,c509_x,c510_x,c511_x
0,-0.6989,-0.2835,-0.3745,0.2183,0.2672,0.4639,0.3310,-0.2546,-0.0922,0.0282,...,-0.0925,-0.3553,0.2894,0.1811,0.4868,-0.2331,0.3297,-0.2008,0.2139,-0.1247
1,-0.5485,-0.3446,-0.2582,0.1820,0.2601,0.3047,0.1262,-0.0564,-0.0477,0.1086,...,0.0165,-0.6867,0.0969,0.2922,0.3346,-0.0379,0.3573,-0.1722,0.4449,-0.1101
2,-0.5095,0.3460,-0.2244,0.8379,0.2165,0.2801,0.1075,-0.5869,0.0947,-0.0272,...,-0.3638,-1.0801,0.3965,0.2226,0.4330,-0.0587,-0.0402,-0.3873,0.2180,-0.2040
3,-0.2009,-1.0129,0.0007,-0.2147,0.1364,0.3085,-0.0481,-0.3183,-0.3490,-0.2213,...,0.3339,-0.7293,0.3420,0.0476,0.3404,0.0126,0.0204,0.0590,0.0514,0.0722
4,-0.5491,0.3073,-0.2957,0.1781,0.2764,-0.1548,0.2062,0.1713,-0.2772,0.2667,...,-0.1145,-1.0393,-0.0791,0.4782,-0.0128,0.3681,0.1120,-0.0035,0.5903,-0.0517

In [188]:
X_train_audio = X_train.iloc[:,547:586]
X_train_audio.head()

,rms_mean,rms_std,zcr_mean,zcr_std,centroid_mean,centroid_std,bandwidth_mean,bandwidth_std,rolloff_mean,rolloff_std,...,mfcc_9_std,mfcc_10_mean,mfcc_10_std,mfcc_11_mean,mfcc_11_std,mfcc_12_mean,mfcc_12_std,tempo,onset_rate,aspect_ratio
0,0.000046,0.000442,0.000834,0.007499,21.680737,188.430586,25.468182,220.781169,53.170711,463.500293,...,0.666802,-0.004744,0.502793,-0.071034,0.874646,-0.048418,0.434218,117.187500,0.083140,1.78
1,0.174383,0.062992,0.104928,0.079074,1753.115951,682.005859,1917.359935,299.301190,3840.053013,1429.255043,...,6.691519,2.107596,6.292175,7.069388,5.010463,1.956412,5.131371,75.000000,4.567647,0.56
2,0.169561,0.075722,0.086965,0.072490,1543.756305,677.810294,1692.903439,370.607104,3257.949219,1403.861300,...,9.563869,-5.520535,9.353555,-0.725174,8.397063,-5.668365,9.189375,98.684211,2.975491,0.55
3,0.458431,0.253745,0.118227,0.147742,2045.340921,1223.702263,1987.538826,566.261725,4177.172658,2151.566882,...,10.105501,4.915122,7.086942,11.301505,7.729668,1.479852,7.784802,144.230769,7.356816,0.57
4,0.400562,0.162019,0.044719,0.029270,1158.172417,636.086741,1553.685133,528.885738,2551.588687,1656.850100,...,8.889380,2.989539,6.543995,6.111625,7.210232,-2.453991,6.410533,93.750000,4.542501,0.56

In [189]:
X_train_meta = X_train.iloc[:,586:609]
X_train_meta.head()

,video_duration,release_year,text_len,nb_hashtags,nb_emojis,hashtag_density,emoji_density,sentiment_score,sentiment_abs,lang_lang_detected_en,...,up_uploader_chamonix_montblanc_off,up_uploader_crans_montana,up_uploader_davosklosters,up_uploader_grandvalira_andorra,up_uploader_kitzbuehel_official,up_uploader_lech_zuers,up_uploader_megeve_officiel,up_uploader_stanton_arlberg_official,up_uploader_tignesofficiel,up_uploader_val_thorens
0,12,2019,131,5,2,0.037879,0.015152,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,10,2019,43,3,2,0.068182,0.045455,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,12,2020,99,10,1,0.100000,0.010000,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,12,2020,89,7,1,0.077778,0.011111,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,11,2020,107,8,1,0.074074,0.009259,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [190]:
X_train_vigg = X_train.iloc[:,632:888]
X_train_vigg.head()

,vggish_000,vggish_001,vggish_002,vggish_003,vggish_004,vggish_005,vggish_006,vggish_007,vggish_008,vggish_009,...,vggish_246,vggish_247,vggish_248,vggish_249,vggish_250,vggish_251,vggish_252,vggish_253,vggish_254,vggish_255
0,-0.266855,-0.050638,-0.119658,0.295781,-0.042799,-0.084526,-0.040336,-0.090752,-0.175160,-0.068950,...,0.009965,0.011114,0.022976,0.014877,0.027410,0.004617,0.030743,0.015930,0.016425,0.044236
1,-0.473632,0.065842,0.274122,-0.695720,-0.235194,-0.782966,-0.244452,-0.543924,-0.159022,-0.251171,...,0.382652,0.315655,0.224860,0.403342,0.364096,0.298637,0.270436,0.240147,0.235235,0.257355
2,-0.775144,-0.039625,0.495350,-0.488526,-0.127453,-0.554972,0.083974,0.040731,0.125101,-0.512650,...,0.219727,0.197428,0.171218,0.414712,0.226970,0.148539,0.321443,0.201648,0.146889,0.171803
3,-0.382426,0.004791,0.090773,-0.655523,0.114082,-0.802606,0.437555,-0.306028,-0.626128,-0.483519,...,0.196941,0.338791,0.096046,0.137372,0.127862,0.183251,0.153921,0.197416,0.155834,0.135674
4,-0.428971,0.389109,0.025493,-0.475513,-0.156904,-0.484427,0.257880,-0.047600,-0.109250,-0.166537,...,0.441250,0.211788,0.106496,0.200837,0.238299,0.106693,0.218670,0.243208,0.263707,0.414421

In [191]:
X_train_old = X_train.iloc[:,np.r_[889:903, 1415:-1]]
X_train_old.head()

,f1_sharpness_y,f1_brightness_y,f1_saturation_y,f2_sharpness_y,f2_brightness_y,f2_saturation_y,f3_sharpness_y,f3_brightness_y,f3_saturation_y,num_cuts_y,avg_motion,camera_shake,yolo_person_y,yolo_ski_snow_y
0,906.615669,163.926991,55.719967,66.125723,149.079250,30.938612,125.613784,155.143706,67.975493,2,0.0000,0.000000,0,0
1,176.830256,136.097022,72.595584,19.779363,159.596410,41.243682,101.408306,137.814554,86.118000,2,2.6792,12.512864,3,1
2,674.164289,120.417032,119.237029,125.024534,123.673109,123.538947,166.550470,120.785476,124.229701,0,0.0000,0.000000,8,0
3,443.495577,139.655132,40.726061,136.465937,153.017789,22.146757,232.673534,177.837891,16.284061,5,2.6353,7.635978,1,1
4,225.248471,151.800220,132.217226,80.894779,154.428752,134.818764,161.962327,156.776094,126.616944,0,0.3202,0.036415,3,1

In [192]:
X_train_old_clip = X_train.iloc[:,903:1415]
X_train_old_clip.head()

,c0_y,c1_y,c2_y,c3_y,c4_y,c5_y,c6_y,c7_y,c8_y,c9_y,...,c502_y,c503_y,c504_y,c505_y,c506_y,c507_y,c508_y,c509_y,c510_y,c511_y
0,-0.5552,-0.1774,-0.3802,-0.0157,0.1021,0.3167,0.1437,-0.1670,-0.0155,0.1198,...,0.2351,-0.6477,0.0394,0.1111,0.2671,-0.1795,0.4840,0.1395,0.1798,-0.1307
1,-0.6422,-0.4321,-0.5333,0.4755,0.1616,0.2027,-0.0085,-0.0775,-0.0955,0.0335,...,0.4371,-0.9457,-0.0714,0.1534,0.1417,0.0733,0.2079,-0.2023,0.1899,-0.0035
2,-0.5143,-0.0685,-0.5232,0.8670,0.4076,0.3934,-0.1508,-0.6172,-0.0478,0.1497,...,-0.2918,-0.9281,0.2439,0.1666,0.3512,0.0739,0.0145,-0.3918,0.4097,-0.0977
3,-0.3089,-0.9013,0.0301,-0.1346,0.1290,0.2999,-0.1833,-0.2298,-0.3499,-0.2697,...,0.2113,-0.9093,0.3641,-0.0142,0.1807,0.2059,0.0811,-0.0500,0.1552,0.1190
4,-0.5272,-0.1774,-0.1920,0.5567,0.3666,0.0507,0.0944,0.1255,-0.2714,0.2321,...,-0.1578,-0.8788,0.2168,0.3198,0.0769,0.2086,-0.0555,-0.2137,0.3197,-0.1434

In [193]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# 1. Toujours centrer et réduire (scaler) avant une PCA
scaler_old_clip = StandardScaler()
X_scaled = scaler_old_clip.fit_transform(X_train_old_clip)

# 2. On instancie la PCA sans fixer le nombre de composantes pour tout voir
pca_old_clip = PCA(n_components=0.95)
X_pca = pca_old_clip.fit_transform(X_scaled)

# 3. Conversion en DataFrame Pandas
# On crée des noms de colonnes dynamiques : PC1, PC2, PC3...
column_names = [f'cold_pc{i+1}' for i in range(X_pca.shape[1])]
X_train_pca_old_clip = pd.DataFrame(data=X_pca, columns=column_names, index=X_train_clip.index)

# --- Affichage des résultats ---
print(f"Nombre de features initiales : {X_train_old_clip.shape[1]}")
print(f"Nombre de composantes retenues : {pca_old_clip.n_components_}")
print(f"Variance totale expliquée : {pca_old_clip.explained_variance_ratio_.sum():.2%}")

# Affichage des premières lignes du nouveau DataFrame
print(X_train_pca_old_clip.head())

Nombre de features initiales : 512
Nombre de composantes retenues : 289
Variance totale expliquée : 95.02%
    cold_pc1  cold_pc2  cold_pc3  cold_pc4  cold_pc5  cold_pc6  cold_pc7  \
0  -4.183227  1.500323  3.351860  4.577343  4.785608 -0.847597 -4.296428
1  -6.029797  0.759009  1.013831  2.987397  5.709417 -3.796646 -6.677899
2 -12.178894  2.042468 -4.074391  3.471441  2.005295 -1.627261 -2.887089
3  -7.819341  8.344071  0.161454  6.085144 -0.293427 -3.710728 -3.381577
4  -9.804375 -0.856175 -2.869819  2.584849  0.769136  1.943855 -5.533994

   cold_pc8  cold_pc9  cold_pc10  ...  cold_pc280  cold_pc281  cold_pc282  \
0 -1.350534  0.574150  -0.354107  ...    0.245196    0.123814    0.049834
1 -2.633927  1.382372  -0.436845  ...   -0.127937   -0.132436    0.120583
2 -1.798362  2.011673  -1.203534  ...    0.529954    0.255923    0.193484
3  0.563070 -6.550913   0.046408  ...   -0.009608   -0.196487   -0.464338
4 -1.334633 -0.529944   0.627056  ...   -0.363210    0.741901   -0.120137

   cold_pc283  cold_pc284  cold_pc285  cold_pc286  cold_pc287  cold_pc288  \
0   -0.061157   -0.397503   -0.325063    0.326072   -0.420199    0.938388
1   -0.460042    0.360586   -0.273841   -0.222418   -0.057928    0.358093
2   -0.890250   -0.407968   -0.719447    0.532593    0.334316   -0.177718
3   -0.062550    0.192795    0.257996   -0.379518    0.162020    0.174656
4   -0.656945   -0.332073   -0.463707    0.494328    0.491973   -0.600286

   cold_pc289
0    0.528138
1    0.173793
2    0.168329
3   -0.199636
4   -0.337972

[5 rows x 289 columns]

In [194]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# 1. Toujours centrer et réduire (scaler) avant une PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train_clip)

# 2. On instancie la PCA sans fixer le nombre de composantes pour tout voir
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_scaled)

# 3. Conversion en DataFrame Pandas
# On crée des noms de colonnes dynamiques : PC1, PC2, PC3...
column_names = [f'c_pc{i+1}' for i in range(X_pca.shape[1])]
X_train_pca_clip = pd.DataFrame(data=X_pca, columns=column_names, index=X_train_clip.index)

# --- Affichage des résultats ---
print(f"Nombre de features initiales : {X_train_clip.shape[1]}")
print(f"Nombre de composantes retenues : {pca.n_components_}")
print(f"Variance totale expliquée : {pca.explained_variance_ratio_.sum():.2%}")

# Affichage des premières lignes du nouveau DataFrame
print(X_train_pca_clip.head())

Nombre de features initiales : 512
Nombre de composantes retenues : 292
Variance totale expliquée : 95.02%
       c_pc1     c_pc2     c_pc3     c_pc4     c_pc5     c_pc6     c_pc7  \
0 -10.952491 -0.323526 -0.652609  2.396329  2.152830 -1.736193 -4.154568
1 -10.130078  0.513408  2.108167  3.352360  2.342843 -3.627221 -5.989041
2 -12.726846  0.225475  1.419669  4.089410  0.017146  1.006140 -0.832937
3  -6.575864  7.466510 -5.562703  3.276916  0.699560 -2.962480 -4.390343
4  -9.272848  0.138569  1.954935  5.129965 -0.791309 -2.140473 -5.889518

      c_pc8     c_pc9    c_pc10  ...   c_pc283   c_pc284   c_pc285   c_pc286  \
0 -3.146676  3.000188 -1.602538  ... -0.699348  0.497151 -0.005927  0.147334
1 -3.791746  0.899109 -0.954176  ...  0.534894  0.864840  0.294123 -0.127219
2 -1.596223  3.610603 -3.650991  ... -0.149751  0.171973  0.724363  0.317161
3  0.255468 -4.731135 -0.460076  ...  0.784113  0.458261  0.203040  0.654659
4 -4.047935 -1.295270 -0.969992  ...  0.682511  0.186144  0.397574  0.546542

    c_pc287   c_pc288   c_pc289   c_pc290   c_pc291   c_pc292
0  0.367090  0.376278 -0.445877  0.464699 -0.277286  0.414742
1 -0.020751 -0.306394 -0.192340 -0.177317 -0.291892  0.067660
2 -0.412311  1.077038  0.425470  0.032867  0.276186 -0.041008
3 -0.771746  0.251044  0.133836  0.301008  0.487699  0.166227
4  0.163524 -0.065753  0.630354  0.426833  0.776142 -0.478627

[5 rows x 292 columns]

In [195]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# 1. Toujours centrer et réduire (scaler) avant une PCA
scaler_vigg = StandardScaler()
X_scaled = scaler_vigg.fit_transform(X_train_vigg)

# 2. On instancie la PCA sans fixer le nombre de composantes pour tout voir
pca_vigg = PCA(n_components=0.95)
X_pca = pca_vigg.fit_transform(X_scaled)

# 3. Conversion en DataFrame Pandas
# On crée des noms de colonnes dynamiques : PC1, PC2, PC3...
column_names = [f'v_pc{i+1}' for i in range(X_pca.shape[1])]
X_train_pca_vigg = pd.DataFrame(data=X_pca, columns=column_names, index=X_train_vigg.index)

# --- Affichage des résultats ---
print(f"Nombre de features initiales : {X_train_vigg.shape[1]}")
print(f"Nombre de composantes retenues : {pca_vigg.n_components_}")
print(f"Variance totale expliquée : {pca_vigg.explained_variance_ratio_.sum():.2%}")

# Affichage des premières lignes du nouveau DataFrame
print(X_train_pca_vigg.head())

Nombre de features initiales : 256
Nombre de composantes retenues : 134
Variance totale expliquée : 95.03%
       v_pc1     v_pc2     v_pc3     v_pc4     v_pc5     v_pc6     v_pc7  \
0 -18.331470  9.533822 -3.096815  4.585328  0.753187 -1.572554 -2.337263
1  21.677959  0.506123 -3.204997  1.955734  5.114941  2.947896  6.695779
2   2.764807 -6.815111  1.641912 -2.412361 -3.554402 -1.398161 -0.898048
3   2.995991 -4.877859 -7.694961  1.895559  2.283132  0.389465  1.014643
4   4.546051 -2.734239 -2.349675  3.159899 -0.671997  5.341449  0.824875

      v_pc8     v_pc9    v_pc10  ...   v_pc125   v_pc126   v_pc127   v_pc128  \
0  0.363385 -1.623859 -1.713059  ...  0.299275  0.148004  0.446878 -0.487273
1  2.741553  2.366865  1.187393  ...  0.251548  0.764113 -0.847283 -1.113890
2  5.188031  0.413806  2.444935  ...  0.414076  0.527754 -0.291776 -0.497952
3 -2.859566 -3.522110 -3.866164  ... -0.126475  1.003060  0.012377 -0.262553
4 -1.717227 -0.301338 -1.617524  ... -0.330512  0.316923 -0.126717  0.051436

    v_pc129   v_pc130   v_pc131   v_pc132   v_pc133   v_pc134
0  0.521267  0.352620 -0.324579 -0.049925 -0.035563  0.267180
1  0.335928  1.427301  0.559234  0.679027  0.186579 -0.091230
2 -0.563064 -0.148910  0.891137  0.096545 -0.591217 -0.990456
3  0.240611 -0.119792  0.428712 -0.348527  0.842811  0.145957
4  0.466589 -0.588061  0.891212  0.246026 -0.877313 -0.537981

[5 rows x 134 columns]

In [196]:
full_df = pd.concat([X_train_pca_clip, y_train], axis=1)
matrix = full_df.corr()
matrix = matrix.abs()
target_corr = matrix['popularity'].sort_values(ascending=False)
print(target_corr.head(20))

popularity    1.000000
c_pc2         0.325956
c_pc4         0.228605
c_pc3         0.198218
c_pc1         0.190434
c_pc7         0.144532
c_pc5         0.132049
c_pc17        0.100396
c_pc10        0.085200
c_pc32        0.082946
c_pc77        0.076130
c_pc64        0.070677
c_pc142       0.064921
c_pc68        0.064446
c_pc92        0.063583
c_pc8         0.063203
c_pc185       0.061651
c_pc36        0.061479
c_pc21        0.061080
c_pc34        0.059571
Name: popularity, dtype: float64

In [197]:
full_df = pd.concat([X_train_pca_old_clip, y_train], axis=1)
matrix = full_df.corr().abs()
target_corr = matrix['popularity'][matrix['popularity'] > SEUIL_OLD]
target_corr = target_corr.drop(labels=['popularity'], errors='ignore')
features_to_keep = target_corr.index.tolist()
X_train_old_clip_filtered = X_train_pca_old_clip[features_to_keep]

# --- Affichage ---X_train_old_clip_filtered
print(f"Nombre de features avant : {X_train_pca_old_clip.shape[1]}")
print(f"Nombre de features après filtrage : {len(features_to_keep)}")
print(f"Variables conservées : {features_to_keep}")

Nombre de features avant : 289
Nombre de features après filtrage : 0
Variables conservées : []

In [198]:
full_df = pd.concat([X_train_pca_clip, y_train], axis=1)
matrix = full_df.corr().abs()
target_corr = matrix['popularity'][matrix['popularity'] > SEUIL_clip]
target_corr = target_corr.drop(labels=['popularity'], errors='ignore')
features_to_keep = target_corr.index.tolist()
X_train_clip_filtered = X_train_pca_clip[features_to_keep]

# --- Affichage ---
print(f"Nombre de features avant : {X_train_pca_clip.shape[1]}")
print(f"Nombre de features après filtrage : {len(features_to_keep)}")
print(f"Variables conservées : {features_to_keep}")

Nombre de features avant : 292
Nombre de features après filtrage : 30
Variables conservées : ['c_pc1', 'c_pc2', 'c_pc3', 'c_pc4', 'c_pc5', 'c_pc7', 'c_pc8', 'c_pc10', 'c_pc13', 'c_pc17', 'c_pc21', 'c_pc32', 'c_pc34', 'c_pc36', 'c_pc44', 'c_pc46', 'c_pc52', 'c_pc60', 'c_pc63', 'c_pc64', 'c_pc68', 'c_pc77', 'c_pc92', 'c_pc108', 'c_pc141', 'c_pc142', 'c_pc185', 'c_pc208', 'c_pc244', 'c_pc292']

In [199]:
full_df = pd.concat([X_train_pca_vigg, y_train], axis=1)
matrix = full_df.corr().abs()
target_corr = matrix['popularity'][matrix['popularity'] > SEUIL_AUDIO]
target_corr = target_corr.drop(labels=['popularity'], errors='ignore')
features_to_keep = target_corr.index.tolist()
X_train_vigg_filtered = X_train_pca_vigg[features_to_keep]

# --- Affichage ---
print(f"Nombre de features avant : {X_train_pca_vigg.shape[1]}")
print(f"Nombre de features après filtrage : {len(features_to_keep)}")
print(f"Variables conservées : {features_to_keep}")

Nombre de features avant : 134
Nombre de features après filtrage : 0
Variables conservées : []

In [200]:
full_df = pd.concat([X_train_old, y_train], axis=1)
matrix = full_df.corr().abs()
target_corr = matrix['popularity'][matrix['popularity'] > SEUIL_OLD]
target_corr = target_corr.drop(labels=['popularity'], errors='ignore')
features_to_keep = target_corr.index.tolist()
X_train_old_filtered = X_train_old[features_to_keep]

# --- Affichage ---
print(f"Nombre de features avant : {X_train_old.shape[1]}")
print(f"Nombre de features après filtrage : {len(features_to_keep)}")
print(f"Variables conservées : {features_to_keep}")

Nombre de features avant : 14
Nombre de features après filtrage : 0
Variables conservées : []

In [201]:
full_df = pd.concat([X_train_video, y_train], axis=1)
matrix = full_df.corr().abs()
target_corr = matrix['popularity'][matrix['popularity'] > SEUIL]
target_corr = target_corr.drop(labels=['popularity'], errors='ignore')
features_to_keep = target_corr.index.tolist()
X_train_video_filtered = X_train_video[features_to_keep]

# --- Affichage ---
print(f"Nombre de features avant : {X_train_video.shape[1]}")
print(f"Nombre de features après filtrage : {len(features_to_keep)}")
print(f"Variables conservées : {features_to_keep}")

Nombre de features avant : 57
Nombre de features après filtrage : 57
Variables conservées : ['f1_sharpness_x', 'f1_brightness_x', 'f1_saturation_x', 'f2_sharpness_x', 'f2_brightness_x', 'f2_saturation_x', 'f3_sharpness_x', 'f3_brightness_x', 'f3_saturation_x', 'f4_sharpness', 'f4_brightness', 'f4_saturation', 'f5_sharpness', 'f5_brightness', 'f5_saturation', 'hook_motion', 'hook_shake', 'content_motion', 'content_shake', 'max_peak_motion', 'yolo_person_x', 'yolo_ski_snow_x', 'avg_face_count_x', 'max_face_coverage_x', 'body_presence_score_x', 'dominant_emotion_angry_x', 'dominant_emotion_disgust', 'dominant_emotion_fear_x', 'dominant_emotion_happy_x', 'dominant_emotion_neutral_x', 'dominant_emotion_none_x', 'dominant_emotion_sad', 'dominant_emotion_surprise', 'num_cuts_x', 'R1', 'G1', 'B1', 'W1', 'R2', 'G2', 'B2', 'W2', 'R3', 'G3', 'B3', 'W3', 'nb_textbloc', 'att_mean_saliency', 'att_max_saliency', 'att_min_saliency', 'att_skewness', 'att_kurtosis', 'att_hook_score', 'att_outro_score', 'att_peak_location', 'att_high_attention_ratio', 'att_attention_instability']

In [202]:
full_df = pd.concat([X_train_meta, y_train], axis=1)
matrix = full_df.corr().abs()
target_corr = matrix['popularity'][matrix['popularity'] > SEUIL]
target_corr = target_corr.drop(labels=['popularity'], errors='ignore')
features_to_keep = target_corr.index.tolist()
X_train_meta_filtered = X_train_meta[features_to_keep]

# --- Affichage ---
print(f"Nombre de features avant : {X_train_meta.shape[1]}")
print(f"Nombre de features après filtrage : {len(features_to_keep)}")
print(f"Variables conservées : {features_to_keep}")

Nombre de features avant : 23
Nombre de features après filtrage : 22
Variables conservées : ['video_duration', 'release_year', 'text_len', 'nb_hashtags', 'nb_emojis', 'hashtag_density', 'emoji_density', 'sentiment_score', 'sentiment_abs', 'up_uploader_alpedhuez', 'up_uploader_avoriaz', 'up_uploader_baqueiraberetoficial', 'up_uploader_chamonix_montblanc_off', 'up_uploader_crans_montana', 'up_uploader_davosklosters', 'up_uploader_grandvalira_andorra', 'up_uploader_kitzbuehel_official', 'up_uploader_lech_zuers', 'up_uploader_megeve_officiel', 'up_uploader_stanton_arlberg_official', 'up_uploader_tignesofficiel', 'up_uploader_val_thorens']

In [203]:
full_df = pd.concat([X_train_audio, y_train], axis=1)
matrix = full_df.corr().abs()
target_corr = matrix['popularity'][matrix['popularity'] > SEUIL_AUDIO]
target_corr = target_corr.drop(labels=['popularity'], errors='ignore')
features_to_keep = target_corr.index.tolist()
X_train_audio_filtered = X_train_audio[features_to_keep]

# --- Affichage ---
print(f"Nombre de features avant : {X_train_audio.shape[1]}")
print(f"Nombre de features après filtrage : {len(features_to_keep)}")
print(f"Variables conservées : {features_to_keep}")

Nombre de features avant : 39
Nombre de features après filtrage : 0
Variables conservées : []

In [204]:
X_train_filtered = pd.concat([X_train.iloc[:,0],
                              X_train_audio_filtered,
                              X_train_clip_filtered,
                              X_train_meta_filtered,
                              X_train_video_filtered,
                              X_train_vigg_filtered,
                              X_train_old_filtered,
                              X_train_old_clip_filtered], axis=1)
# --- Affichage ---
print(f"Nombre de features après : {X_train_filtered.shape[1]}")

Nombre de features après : 110

In [205]:
X_train_filtered.head()

,video_id,c_pc1,c_pc2,c_pc3,c_pc4,c_pc5,c_pc7,c_pc8,c_pc10,c_pc13,...,att_mean_saliency,att_max_saliency,att_min_saliency,att_skewness,att_kurtosis,att_hook_score,att_outro_score,att_peak_location,att_high_attention_ratio,att_attention_instability
0,6739804771013774597,-10.952491,-0.323526,-0.652609,2.396329,2.152830,-4.154568,-3.146676,-1.602538,-1.905392,...,18.507618,22.806738,10.112532,-1.205898,2.290891,19.101084,17.134331,0.576923,0.961538,1.628250
1,6750983141873224966,-10.130078,0.513408,2.108167,3.352360,2.342843,-5.989041,-3.791746,-0.954176,-2.820935,...,17.008192,21.973700,12.307789,0.156576,-0.054742,13.983650,18.627373,0.545455,0.954545,1.496439
2,6792131260543225094,-12.726846,0.225475,1.419669,4.089410,0.017146,-0.832937,-1.596223,-3.650991,-2.406425,...,16.193535,20.542313,13.786904,0.872993,0.066454,17.384562,15.784161,0.192308,1.000000,0.600385
3,6792133610360065285,-6.575864,7.466510,-5.562703,3.276916,0.699560,-4.390343,0.255468,-0.460076,0.047442,...,14.890491,18.952852,11.925114,0.715640,0.095493,17.447706,15.095791,0.800000,0.920000,1.379394
4,6793347939294072069,-9.272848,0.138569,1.954935,5.129965,-0.791309,-5.889518,-4.047935,-0.969992,-3.676326,...,15.241565,17.432913,12.499903,-0.753328,-0.171700,15.479694,16.617624,0.913043,0.869565,0.853227

In [206]:
X_train_filtered.to_csv("../features/global_features/X_train_filtered.csv",index=False)

In [207]:
# 1. Découpage des blocs du X_test (même logique que pour X_train)
X_test_video_raw = X_test.iloc[:, np.r_[:23, 535:547, 609:632]]
X_test_clip_raw = X_test.iloc[:, 23:535]
X_test_audio_raw = X_test.iloc[:, 547:586]
X_test_meta_raw = X_test.iloc[:, 586:609]
X_test_vigg_raw = X_test.iloc[:, 632:888]
X_test_old_raw = X_test.iloc[:,np.r_[889:903, 1415:-1]]
X_test_old_clip_raw = X_test.iloc[:,903:1415]

# 2. Transformation PCA du bloc 'clip'
# Note: On utilise le scaler et la pca du train (cellule 60)
X_test_old_clip_raw = scaler_old_clip.transform(X_test_old_clip_raw) # Utilisez le scaler de la cellule 60
X_test_old_clip_pca = pca_old_clip.transform(X_test_old_clip_raw)    # Utilisez la pca de la cellule 60
X_test_pca_old_clip = pd.DataFrame(X_test_old_clip_pca, columns=[f'cold_pc{i+1}' for i in range(X_test_old_clip_pca.shape[1])], index=X_test.index)

# 2. Transformation PCA du bloc 'clip'
# Note: On utilise le scaler et la pca du train (cellule 60)
X_test_clip_scaled = scaler.transform(X_test_clip_raw) # Utilisez le scaler de la cellule 60
X_test_clip_pca = pca.transform(X_test_clip_scaled)    # Utilisez la pca de la cellule 60
X_test_pca_clip = pd.DataFrame(X_test_clip_pca, columns=[f'c_pc{i+1}' for i in range(X_test_clip_pca.shape[1])], index=X_test.index)

# 3. Transformation PCA du bloc 'vigg'
# Note: On utilise le scaler et la pca du train (cellule 61)
# Attention: Si vous avez écrasé les variables 'scaler' et 'pca', il faudra les renommer dans votre code train
X_test_vigg_scaled = scaler_vigg.transform(X_test_vigg_raw) 
X_test_vigg_pca = pca_vigg.transform(X_test_vigg_scaled)
X_test_pca_vigg = pd.DataFrame(X_test_vigg_pca, columns=[f'v_pc{i+1}' for i in range(X_test_vigg_pca.shape[1])], index=X_test.index)

In [208]:
# Sélection des colonnes déjà filtrées pour chaque bloc
X_test_audio_filtered = X_test_audio_raw[X_train_audio_filtered.columns]
X_test_clip_filtered = X_test_pca_clip[X_train_clip_filtered.columns]
X_test_meta_filtered = X_test_meta_raw[X_train_meta_filtered.columns]
X_test_video_filtered = X_test_video_raw[X_train_video_filtered.columns]
X_test_vigg_filtered = X_test_pca_vigg[X_train_vigg_filtered.columns]
X_test_old_filtered = X_test_old_raw[X_train_old_filtered.columns]
X_test_old_clip_filtered = X_test_pca_old_clip[X_train_old_clip_filtered.columns]

# Concaténation finale
X_test_filtered = pd.concat([
    X_test.iloc[:,0],
    X_test_audio_filtered,
    X_test_clip_filtered,
    X_test_meta_filtered,
    X_test_video_filtered,
    X_test_vigg_filtered,
    X_test_old_filtered,
    X_test_old_clip_filtered
], axis=1)

print(f"Nombre de features X_test après : {X_test_filtered.shape[1]}")
# Vérification que les colonnes sont identiques au train
assert all(X_test_filtered.columns == X_train_filtered.columns)

Nombre de features X_test après : 110

In [209]:
X_test_filtered.to_csv("../features/global_features/X_test_filtered.csv", index=False)